{"version":1,"defects":{"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #0":4,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #1":4,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #2":4,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #3":4,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #4":4,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #5":4,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #6":4},"times":{"Tests\\Unit\\RouterTest::it_registers_a_route":0.019,"Tests\\Unit\\RouterTest::it_registers_a_get_route":0,"Tests\\Unit\\RouterTest::it_registers_a_post_route":0,"Tests\\Unit\\RouterTest::it_registers_a_delete_route":0,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #0":0.02,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #1":0,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #2":0,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #3":0,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #4":0,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #5":0,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #6":0}}